import { withMainLayout } from "@/shared/layouts/MainLayout/Layout";
import Head from "next/head";
import { AccountPageComponent } from "@/modules/AccountModule/page-components/AccountPageComponent/AccountPageComponent";

function Account() {
  return (
    <>
      <Head>
        <title>account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AccountPageComponent />
    </>
  );
}

export default withMainLayout(Account);
